
// Objective-C API for talking to the following Go packages
//
//	github.com/netbridge/nbvpn/mobile/obfs2bridge
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Obfs2bridge_FRAMEWORK_H__
#define __Obfs2bridge_FRAMEWORK_H__

#include "Obfs2bridge.objc.h"
#include "Universe.objc.h"

#endif
