// Objective-C API for talking to github.com/netbridge/nbvpn/mobile/obfs2bridge Go package.
//   gobind -lang=objc github.com/netbridge/nbvpn/mobile/obfs2bridge
//
// File is generated by gobind. Do not edit.

#ifndef __Obfs2bridge_H__
#define __Obfs2bridge_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Running reports whether the bridge is active.
 */
FOUNDATION_EXPORT BOOL Obfs2bridgeRunning(void);

/**
 * Start launches the obfs2 client bridge (multi-channel, multi-entry,
auto-reconnect). serverAddrs is a comma-separated entry pool such as
"1.2.3.4:443,1.2.3.4:8443"; pskHex is the hex-encoded PSK; localUDP is the
local UDP port the bridge listens on (WireGuard Endpoint must point at
127.0.0.1:localUDP); insecure allows self-signed server certs; channels is
the parallel tunnel count.
 */
FOUNDATION_EXPORT BOOL Obfs2bridgeStart(NSString* _Nullable serverAddrs, NSString* _Nullable pskHex, long localUDP, BOOL insecure, long channels, NSError* _Nullable* _Nullable error);

/**
 * Stop terminates the bridge.
 */
FOUNDATION_EXPORT void Obfs2bridgeStop(void);

#endif
